FROM mysql:5.7
ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_DATABASE todos_db
ENV MYSQL_USER todos
ENV MYSQL_PASSWORD todos
ADD schema.sql /docker-entrypoint-initdb.d/
ADD seeds.sql /docker-entrypoint-initdb.d/
EXPOSE 3306
